#!/bin/bash
NODE=$1
S="sporestack"
SPORE="node.sporestack.com"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SSH="ssh -t -o StrictHostKeyChecking=no root@$NODE.$SPORE"

hr() {
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' ${1:--}
}

if [[ ! $(command -v $S) ]]; then
    echo "Install sporestack first: \"pip3 install sporestack || pip install sporestack\""
    exit 1
fi

echo "1. Make sure you have about \$1 worth of BCH available to spend in a wallet of your choosing"
echo "2. Have a GINcoin address to receive rewards (you can get one in the GINcoin QT wallet)"
echo -n "3. Press [ENTER] to continue..."
read tmp
hr

if [[ ! $NODE ]]; then
    echo "Building new server..."
    exec 5>&1
    OUTPUT=$(sporestack spawn --days 1 --osid 215 --dcid AUTO --flavor 201 | tee >(cat - >&5))
    NODE="${OUTPUT##*$'\n'}"
    SSH="ssh -t -o StrictHostKeyChecking=no root@$NODE.$SPORE"
    echo "In case you need to resume setup use $NODE as a the first parameter to this command"
    hr
    echo "Initializing..."
    sleep 5

    $SSH "$(<$DIR/masternode-hot-init.sh)"
    echo "Waiting 30 sec..."
    sleep 30
fi

$SSH "$(<$DIR/masternode-hot-init.sh)"